### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by lixiii** [yl573/catalearn#1]
```
Collecting git+https://github.com/yl573/catalearn
  Cloning https://github.com/yl573/catalearn to /private/var/folders/35/_wb8g8sd069ftgv0qf2j3tw40000gn/T/pip-x6pfraud-build
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/catalearn.egg-info
    writing pip-egg-info/catalearn.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/catalearn.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/catalearn.egg-info/requires.txt
    writing top-level names to pip-egg-info/catalearn.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/catalearn.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/catalearn.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/catalearn.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/35/_wb8g8sd069ftgv0qf2j3tw40000gn/T/pip-x6pfraud-build/setup.py", line 24, in <module>
        copyfile('./catalearn_magic.py', os.path.expanduser('~/.ipython/profile_default/startup/catalearn_magic.py'))
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 121, in copyfile
        with open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/lixiii/.ipython/profile_default/startup/catalearn_magic.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/35/_wb8g8sd069ftgv0qf2j3tw40000gn/T/pip-x6pfraud-build/
```

**Comment by lixiii** [comment]
My `pip3 list`

```
appnope (0.1.0)
bleach (2.0.0)
decorator (4.0.11)
entrypoints (0.2.3)
html5lib (0.999999999)
ipykernel (4.6.1)
ipython (6.1.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
MarkupSafe (1.0)
mistune (0.7.4)
nbconvert (5.2.1)
nbformat (4.3.0)
notebook (5.0.0)
pandocfilters (1.4.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.14)
ptyprocess (0.5.2)
Pygments (2.2.0)
python-dateutil (2.6.0)
pyzmq (16.0.2)
qtconsole (4.3.0)
setuptools (32.2.0)
simplegeneric (0.8.1)
six (1.10.0)
terminado (0.6)
testpath (0.3.1)
tornado (4.5.1)
traitlets (4.3.2)
wcwidth (0.1.7)
webencodings (0.5.1)
wheel (0.29.0)
widgetsnbextension (2.0.0)
```
